# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 279)
        Form.setStyleSheet("QWidget {\n"
"    background-color:  rgb(245, 195, 208);\n"
"}")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(9, 17, 281, 65))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 5px solid rgb(225, 114, 141);\n"
"    border-radius: 10px;\n"
"    font-size: 25px;\n"
"    text-align: right;\n"
"    padding: 5px;\n"
"    color: black;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 278, 180))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 0, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 0, 2, 1, 1)
        self.pushButton_divide = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_divide.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.gridLayout.addWidget(self.pushButton_divide, 0, 3, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clear.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 4, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_times = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_times.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_times.setObjectName("pushButton_times")
        self.gridLayout.addWidget(self.pushButton_times, 1, 3, 1, 1)
        self.pushButton_oPar = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_oPar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_oPar.setObjectName("pushButton_oPar")
        self.gridLayout.addWidget(self.pushButton_oPar, 1, 4, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout.addWidget(self.pushButton_1, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.pushButton_minus = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_minus.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.gridLayout.addWidget(self.pushButton_minus, 2, 3, 1, 1)
        self.pushButton_cPar = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_cPar.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_cPar.setObjectName("pushButton_cPar")
        self.gridLayout.addWidget(self.pushButton_cPar, 2, 4, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout.addWidget(self.pushButton_0, 3, 0, 1, 1)
        self.pushButton_00 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_00.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_00.setObjectName("pushButton_00")
        self.gridLayout.addWidget(self.pushButton_00, 3, 1, 1, 1)
        self.pushButton_dec = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dec.setStyleSheet("QPushButton {\n"
"    background-color: rgb(247, 227, 233);\n"
"    border: 2px solid rgb(225, 114, 141);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_dec.setObjectName("pushButton_dec")
        self.gridLayout.addWidget(self.pushButton_dec, 3, 2, 1, 1)
        self.pushButton_plus = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_plus.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.gridLayout.addWidget(self.pushButton_plus, 3, 3, 1, 1)
        self.pushButton_equal = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_equal.setStyleSheet("QPushButton {\n"
"    background-color: rgb(225, 114, 141);\n"
"    border: 2px solid rgb(202, 97, 129);\n"
"    border-radius: 8px;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    min-height: 30px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F5F5DC;\n"
"}")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.gridLayout.addWidget(self.pushButton_equal, 3, 4, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pretty Calc"))
        self.lineEdit.setPlaceholderText(_translate("Form", "       ✨ Girl Math ✨"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_divide.setText(_translate("Form", "/"))
        self.pushButton_clear.setText(_translate("Form", "C"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_times.setText(_translate("Form", "*"))
        self.pushButton_oPar.setText(_translate("Form", "("))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_minus.setText(_translate("Form", "-"))
        self.pushButton_cPar.setText(_translate("Form", ")"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_00.setText(_translate("Form", "00"))
        self.pushButton_dec.setText(_translate("Form", "."))
        self.pushButton_plus.setText(_translate("Form", "+"))
        self.pushButton_equal.setText(_translate("Form", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
